name: Create Azure Resources

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          version: '2.42.0'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create resources using Bicep
        run: |
          az deployment group create \
            --resource-group ${{ vars.AZURE_RG }} \
            --template-file ./config/main.bicep \
            --parameters namePrefix=${{ vars.AZURE_PREFIX }}
